CREATE TABLE IF NOT EXISTS `HeroSection` (
  `id` VARCHAR(191) NOT NULL,
  `eyebrow` VARCHAR(80) NOT NULL,
  `headlinePrefix` VARCHAR(80) NOT NULL,
  `headlineAccent` VARCHAR(80) NOT NULL,
  `headlineSuffix` VARCHAR(120) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `role` VARCHAR(80) NOT NULL,
  `techTags` JSON NOT NULL,
  `primaryCtaLabel` VARCHAR(80) NOT NULL,
  `primaryCtaTarget` VARCHAR(80) NOT NULL,
  `secondaryCtaLabel` VARCHAR(80) NOT NULL,
  `secondaryCtaHref` VARCHAR(191) NOT NULL,
  `avatarUrl` VARCHAR(191) NULL,
  `avatarAlt` VARCHAR(120) NOT NULL,
  `githubUrl` VARCHAR(191) NULL,
  `linkedinUrl` VARCHAR(191) NULL,
  `twitterUrl` VARCHAR(191) NULL,
  `statusBadgeLabel` VARCHAR(80) NOT NULL,
  `statusBadgeDetail` VARCHAR(80) NOT NULL,
  `scrollIndicatorLabel` VARCHAR(40) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
