CREATE TABLE IF NOT EXISTS `AdminSession` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `expiresAt` DATETIME(3) NOT NULL,
  `revokedAt` DATETIME(3) NULL,
  `lastSeenAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `AdminSession_userId_idx` (`userId`),
  CONSTRAINT `AdminSession_userId_fkey`
    FOREIGN KEY (`userId`) REFERENCES `User`(`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `Project` MODIFY COLUMN `description` TEXT NOT NULL;
ALTER TABLE `Experience` MODIFY COLUMN `description` TEXT NOT NULL;
ALTER TABLE `HeroSection` MODIFY COLUMN `description` TEXT NOT NULL;
